fsspec/s3fs

s3fs/core.py, s3fs/tests/test_s3fs.py
Test shows that this is very slow - or at least, calling ls on the bucket
every time a new file is created is very slow.
Fixes #17  (but not the final solution, I suspect)
=> ls using pagination

s3fs/core.py
Where credenitals are present for boto3, makes no discernable difference
Fixes #11 
Have not thought of a decent way to test this - what credentials should be in place in Travis, and wouldn't moto accept everything?
=> Allow anon=None, in which case try False, then True

s3fs/core.py, s3fs/tests/test_s3fs.py
Adds retries on write: raises after 10 tries by default. Recommend to catch that, and truncate at that point (self f.buffer to empty io.BytestIO, and call close()), could be done automatically.
Marge does multi-part copying on the server side, to allow splitting of big file and parallel upload.
Append mode either makes first chunk be the existing file (if size>=5MB) or downloads existing data if small. This means that the original file will *briefly* not exist.
=> Append wretry merge

s3fs/core.py, s3fs/tests/test_s3fs.py
in S3File._fetch, caused missing bytes at the end of a file when
reading blocks big compared to the file blocksize.
=> Fix mistery big

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes for pandas interoperability
- `S3File.info()` to call client.head_object rather than going through S3FileSystem's info, which calls client.list_objects; 
the latter will fail if some keys cannot be accessed. Thus, can still open files where we know the key beforehand. This
means that the two `info()` methods do not do wuite the same thing.
- add checks for ParamValidationError, which can occur (instead of ClientError) for illegal bucket names
=> Direct info

s3fs/core.py, s3fs/tests/test_s3fs.py
This is to enable passing around credentials inside distributed
without using the raw key/secret from the user
=> PR: Allow creation of temporary credentials

s3fs/core.py, s3fs/mapping.py, s3fs/tests/test_mapping.py, s3fs/tests/test_s3fs.py
This adds a classmethod, `S3FileSystem.current()` which returns the most recently created `S3FileSystem` object.  It uses this method within `S3Map` to allow behavior like the following without explicitly creating an s3 object.
```python
d = S3Map('bucketname/directory')
```
=> Default S3FileSystem

s3fs/core.py, s3fs/tests/test_s3fs.py, s3fs/utils.py
Previously on touch or write events we called `_ls` to update the local
cache.  When we called touch repeatedly this caused a slowdown unless
we used the `no_refresh` context manager.
Now we just invalidate the cache on write events so that the next read
event will correctly update the cache.  This helps with many successive
writes.
cc @martindurant 
This still has a couple of failures.  I'm probably doing something a bit wacky.
=> Invalidate rather than update cache

s3fs/core.py, s3fs/mapping.py, s3fs/tests/test_mapping.py, s3fs/tests/test_s3fs.py
For small writes can make a decent speed improvement to turn SSL off, reducing connection overhead.
Also, fix error on Mapping's clear(): the "root" shouldn't need to exist
=> PR: Expose use_ssl option for S3 client

s3fs/core.py, s3fs/tests/test_s3fs.py
bulk delete takes a list of keys to remove, which must be in the same bucket.
rm, recursive, calls this instead of iterating over individual files, will
be much faster in the case of many files.
Fixes #40  - particularly useful for `clear()` on mappings.
=> PR: Add bulk delete

s3fs/core.py, s3fs/mapping.py, s3fs/tests/test_mapping.py
1.  Create a directory for mapping if it doesn't exist.
2.  Include original exception error messages
=> Various small changes

s3fs/core.py, s3fs/tests/test_s3fs.py
Otherwise bucket name would still show up for `ls('')`.
Fixes #43
=> PR: When deleting bucket, invalidate list cache for ''

s3fs/core.py, s3fs/tests/test_mapping.py, s3fs/tests/test_s3fs.py
Designed to get around the case where some parts of a bucket are not accessible
Fixes #38 
@jseabold , please see if this fixes things for you.
=> PR: Rewrite ls to use prefixes

s3fs/core.py, s3fs/tests/test_s3fs.py
If relying on a cached connection object, was not creating session
object to go with it.
=> PR: Fix bad connection caching

docs/source/index.rst, s3fs/core.py, s3fs/tests/test_s3fs.py
Must now be explicitly specified True or False - no attempt to use
credentials with fallback. No check of successful credentials is made,
error will only happen when an operation is attempted.
If not explicitly provided, but not anonymous, delegation token will
not call STS, but assume that whatever mechanism allowed connection
is available to other S3FileSystem instances (which are potentially on
other machines in the dask-distributed contexct)
Changed docs to reflect these changes, with a short section on
credential usage
Related: https://github.com/dask/dask/issues/1178 https://github.com/dask/dask/pull/1184
=> Anon no longer defaults to None

s3fs/core.py, s3fs/tests/test_s3fs.py
For buckets not associated with user, e.g., all buckets where
`anon=True`.
Fixes #53
=> Fix exists for buckets

s3fs/core.py, s3fs/tests/test_s3fs.py
Can only used the canned ACLs, nothing role-based. Good enough for
read/write, private/public.
Unfortunately, moto does not enable testing of ACLs - even anonymous users can access everything. I have tested on real S3, and urge others to do so too.
Note that there is no way to actually display the set ACL, but the effects should be noticeable for other users.
Fixes #47 
Additional commit Fixes #57
=> Add ACL on create, and chmod

s3fs/core.py, s3fs/tests/test_s3fs.py
When S3FileSystem.put is used, because chunks are written to
S3File.write in chunks `blocksize` large this results in multipart
uploads that are twice as large, because it takes two writes in order to
surpass `blocksize` number of bytes in the buffer. This change will
cause it to send parts that are equal to `blocksize` when using put.
I have had consistent problems with connection timeouts to s3 with
larger files. With this simple change, I have uploaded many large files
with no problems. I also plan to submit a pull request that allows you
to override the blocksize from S3FileSystem APIs. I hope this is welcome.
=> Allow parts of multipart upload to be equal to the blocksize

s3fs/core.py
I was getting S3 timeout errors.  These became harder to identify in recent versions because all of the timeout errors moved.  From tracebacks it looks like they're now deep within vendored versions of other libraries. 
Rather than try to track these I'm now excepting on *any* exception that contains the text `time`.  This is a hack.  Alternatives welcome.
=> Continue on more timeout errors

s3fs/core.py, s3fs/tests/test_s3fs.py
Keywords to allow non-cache filling behaviour and default block size applied on FileSystem, so that they don't need to be used within `open`.
Fixes #78
=> Add default parameters

s3fs/core.py, s3fs/tests/test_s3fs.py
Hi, 
Thanks for this project. It makes working with S3 so much simpler.
Could you add support for S3 metadata? Here is an initial implementation, where I tried to mimic the [xattr Linux interface][1]. Let me know if I should change something.
Thanks!
Pablo
[1]: https://manpages.debian.org/jessie-backports/manpages/xattr.7.en.html
=> Add support for metadata via {set,get}xattr calls

s3fs/core.py, s3fs/tests/test_s3fs.py
Was looking at using your s3fs for my purposes in an AWS app. One issue I ran into during testing of my app was a failure to bulk remove the s3fs test resources at the end of my test. It seems like there may be some kind of 'separation of concerns' issue going on with the refresh logic. As far as I can tell a particular S3 key is only recognized as a DIRECTORY type key during an '_lsdir' operation. The consequence being that if I do an 'ls' operation and then add a file under a particular key another 'ls' operation must occur before I can successfully bulk remove (remove with recursion) the contents under that key.
The contents of this GITHUB branch (named 'mkdir') demonstrate the problem and one possible solution. The quick fix solution is one line in core.py (see the code diffs). It is …
=> Provide failing unit test to demonstrate missing refresh logic.

s3fs/core.py
It was a bit confusing in documentation as token is an accepted parameter,
yet it wasn't included in the docstring (and therefore the generated API docs).
Also used more standard AWS terminology for key/secret/token names.
=> Added token parameter to S3FileSystem docstring

s3fs/core.py, s3fs/tests/test_s3fs.py
It may have other applications for other use cases, but in my case, I need to be able to pass `signature_version='s3v4'` to the `botocore.client.Config` object in order to use s3fs with [Minio](https://minio.io).
=> add `config_kwargs` parameter to S3FileSystem

s3fs/core.py
Recently there have been additional kwargs that are aggregated so
that can be passed through when calling boto methods. These aren't
currently being used. This uses them.
=> Use additional kwargs

s3fs/core.py, s3fs/tests/test_s3fs.py
The current behavior of raising an assertion causes some small files to be unwritable.
For example, with [`io.TextIOWrapper`](https://docs.python.org/2/library/io.html#io.TextIOWrapper) used by `dask.bytes`, a `close()` call internally first calls a `flush()`. And if the buffer was less than the block size, the exception would be raised and the file couldn't be written.
=> Simply ignore flushes if buffer smaller than block size

s3fs/core.py, s3fs/tests/test_s3fs.py
This fixes #97; I'd be grateful for pointers on how to write tests exposing the problem.
=> filter all kwargs in _call_s3 to prevent botocore ParamValidationError (issue #97)

s3fs/core.py, s3fs/tests/test_s3fs.py
In the current implementation in order to open a key for read, info method is called, which subsequently performs _ls on file's "directory". This feature makes it impossible to use s3fs when there is a lot of keys under a prefix.
Since one of the most common ways of using s3 is like a key/val store, where metadata about keys are stored in rds and s3 is used as a cheap storage, it would to support this usa case.
=> Change underlying implementation of info

docs/source/index.rst, s3fs/core.py, s3fs/tests/test_s3fs.py
When s3 is used with bucket versioning this adds additional safely to reading objects preventing potential inconsistent state when reading an object whilst something else writes to it.
This also adds a utility to specifically open a given version of the file.
For non-version enabled buckets this should have no change.
=> Add support for bucket versioning

.gitignore, .travis.yml, MANIFEST.in, s3fs/core.py, s3fs/tests/test_s3fs.py, s3fs/tests/test_utils.py, s3fs/utils.py, test_requirements.txt
* Fix a couple asserts in tests that were either missing or misplaced. For example, one assert was outside the loop it was supposed to be in.
* Remove custom `tmpfile` context manager, since `pytest` has a built-in one. I pegged `pytest` to ≥ 2.7.3 because it has a bugfix that's nice to have for temporary files.
* Use set literal notation in a few places for cleaner code. Also avoids global lookups.
* Add `futures` as a test requirement for Python 2. It was working by chance since it's an indirect dependency of another package.
* Move test requirements to their own file so developers can easily install them locally with pip
* Add a few things to `.gitignore` -  `pytest`'s new cache directory and the `virtualenv` environment file for those of us who don't use conda. 🙂 
* Removed an …
=> Minor code cleanup and unit test fixes

s3fs/core.py, s3fs/tests/test_s3fs.py
#139 add region_name to create_bucket
=> #139 add region_name to create_bucket

requirements.txt, s3fs/core.py
This is an attempt to get some better exception handling for s3fs.
closes #118
The one key change here is that if a user lacks permissions to a directory `ls` will raise instead of silently returning nothing.  
Alternatively we could throw a warning here.
=> Use raise_from from six in order to provide more context for failures.

.travis.yml, requirements.txt, s3fs/core.py, s3fs/tests/test_s3fs.py, test_requirements.txt
As per the title, implement `S3FileSystem.isfile` and `isdir`. These will be still useful even after `s3fs` is derived from [fsspec](https://github.com/martindurant/filesystem_spec). `isdir` in particular:
- cannot be delegated to an `s3.info()` call since this would raise `FileNotFoundError` 
- is relatively inexpensive regardless of the number of files in the directory, unlike `ls`.
=> Implement isfile and isdir

s3fs/core.py, s3fs/tests/test_s3fs.py, test_requirements.txt
1) ``flush()`` was properly ensuring that the buffer had reached at
least ``block_size`` in length before writing a part to S3; however, it
was not ensuring that resulting part(s) were themselves at all on the
order of ``block_size``.
2) Nor did the method ensure every part is less than S3's maximum part
size, (regardless of desired ``block_size``).
---
(1) was relatively "easy" to cross -- if a single ``write()`` payload
was of *any* size equal to or greater than ``buffer_size`` -- even many
times larger than ``buffer_size`` -- it was uploaded as is, as a single
part. This itself caused ``flush()`` to violate the expectation of
``buffer_size``, and to operate differently depending on whether the
user wrote their payload in small chunks or big chunks.
Moreover, (1) caused a breaking …
=> support for large writes & test updates

s3fs/core.py, s3fs/errors.py, s3fs/tests/test_s3fs.py
Right now, if you try reading a file with expired credentials, you get a `FileNotFoundError`. This is pretty confusing. Now that we support Python 3 only, we can be *much* more specific about the kinds of errors we're throwing.
I pulled a list of all the S3 error codes from [here](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html) and made approximations of what the most logical error code could be.
* When attempting to delete a nonexistent bucket, an `IOError` was thrown with the message "not empty." The proper exception is a `FileNotFoundError` because the bucket wasn't found.
* Fixed a number of `IOError` calls that were passing invalid arguments. According to [the documentation](https://docs.python.org/3/library/exceptions.html#OSError), if multiple arguments are …
=> Make boto3 exceptions more accurate

s3fs/core.py
The output doesn't change, we just prevent the extra lookup if it is not
needed
Fixes #200
=> Only list parent in ls if files were not found

s3fs/core.py, s3fs/tests/test_s3fs.py
This adds in autocommit to the .open api.  Seems it was missing?
=> Missing autocommit for fs.open()

s3fs/core.py, s3fs/tests/test_s3fs.py
Related to #213. The motivation is that sometimes we want to turn off caching by default (e.g. when reading parquet files with threads)
Since different fsspec implementations overrides `_open()` differently, I've chosen to add `default_cache_type` to `s3fs` instead of `fsspec`
=> allow setting default S3File's cache_type in S3FileSystem

.gitignore, setup.cfg
Universal wheels are for packages that work with Python 2 & 3.
=> PKG: Remove universal wheels

s3fs/core.py, s3fs/tests/test_s3fs.py
When not autocommitting the mpu that is created is the best way to
ensure that transactional style commits can be performed elsewhere.
Alternatively we could add another flag to S3File that controls this
=> Always use multipart uploads when not autocommitting

docs/source/api.rst
`S3Map` was changed from a class to a function in #161. This PR updates the sphinx autosummary accordingly.
Closes #250
=> Use autofunction for S3Map sphinx autosummary

docs/source/changelog.rst, docs/source/conf.py, docs/source/index.rst
This PR adds a changelog page to the documentation. I've included entries for all PRs merged since the latest release (`0.3.5`). 
Closes #147
=> Add changelog to docs

s3fs/core.py, s3fs/tests/test_s3fs.py
@TomAugspurger , I wonder if you think this might finally fix the auth problems. Now, the super init is only called after connect. This is important, because the super init sets the cached flag, which then skips the rest of the init for a new invokation - this means that it might have been possible for one invocation of the same instance to be done with init while another call of the same thing is still undergoing connect().
=> Don't call super init until init is done

s3fs/core.py, s3fs/tests/test_s3fs.py
Precursor to https://github.com/intake/filesystem_spec/pull/181.
It seems that with that refactor, some of additional state lives between tests, which is causing failures.
```
=================================== FAILURES ===================================
____________________ test_pickle_without_passed_in_session _____________________
s3 = <s3fs.core.S3FileSystem object at 0x7ff133337b50>
def test_pickle_without_passed_in_session(s3):
import pickle
s3 = S3FileSystem()
>       pickle.dumps(s3)
E       AttributeError: Can't pickle local object 'lazy_call.<locals>._handler'
```
I don't fully understand what is actually different, but removing instance caches between tests "fixes" it.
=> TST: Clear instance cache between tests.

s3fs/core.py
This can help avoid potentially unexpected long calls when the parent directory contains many subdirectories which must all be listed. This also uses self._ls under the hood so the dircache still gets filled and used.
=> Override isdir to not include parent directory ls #258

s3fs/core.py, s3fs/tests/test_s3fs.py
This allows files opened from a filesystem created with
request_payer=True to also be accessed with the appropriate
RequestPayer headers.
Currently, the requester_pays kwarg to S3FileSystem only works for listing keys, etc., but has no effect when you actually open a file to read data. The following will thus result in an access denied error:
```
fs = s3fs.S3FileSystem(requester_pays=True)
with fs.open("bucket/key") as f:
print(f.read())
```
There doesn't seem to be any way to specify that the file object should also be requester_pays, and I think it makes sense that this should be the default.
In the meantime, for anyone else running into this issue, here's a monkey patch that I'm currently using which accomplishes the same thing.  Probably also illustrates why it'd be much easier to …
=> Propagate req_kw from the filesystem to opened files.

s3fs/core.py
s3a:// is the official schema used by Hadoop (s3 and s3n are deprecated in hadoop-aws jar)
https://cwiki.apache.org/confluence/display/HADOOP2/AmazonS3
Motivation: Be able to keep a consistent fs scheme across different PySpark, s3fs/PyArrow calls
=> Add more s3 fs schemes (s3a://, s3n://)

docs/source/index.rst, s3fs/core.py
Allows people to opt-in to the basic logger config which outputs s3fs
messages while by default avoiding interfering with application-level
logging config.
The premise for piggy-backing on S3FS_LOGGING_LEVEL is that anyone
setting it expects to see some log output.  Anyone who doesn't want to
see log output can either not set it themselves or ensure it is unset
before s3fs is loaded.
Resolves #282.
=> Only configure the logger if S3FS_LOGGING_LEVEL is set

README.rst, docs/requirements.txt, docs/source/index.rst, requirements.txt, s3fs/core.py, s3fs/tests/test_s3fs.py
Given the discussion in #276 I wanted to do a quick POC to see what it would be like to switch s3fs to `botocore` instead of `boto3`.
Most of the changes here are just switching library names and slightly tweaking the way the sessions are constructed as there are some minor differences (keys are given to the client, not the session).
All calls to S3 have remained exactly the same as `boto3` is just handing off to `botocore` underneath with one notable exception.
The `client('s3').copy()` method is not available in `botocore` and after having a dig through the `boto3` codebase it seems quite involved to implement as it enables multi-threaded multi-part transfers between buckets. However I did notice there was an unused `copy_basic` method already implemented which uses the API …
=> Switch to botocore

s3fs/core.py, s3fs/tests/test_s3fs.py
- Implement `S3FileSystem.checksum` that exposes the `refresh` parameter
- For files, use the ETag field for this purpose; for directories, use a hash of the output of `ls(path, detail=True)`, similar to the default implementation in `AbstractFileSystem`; if the path contains multiple files/directories, use a hash of the list of checksums of the individual items
=> Implement checksum for S3FileSystem

s3fs/core.py, s3fs/tests/test_s3fs.py
When initiliazing an S3FileSystem object, it is possible to configure the botocore session as per the parameter "config_kwargs". However, if one tries to configure the config parameters "connect_timeout" or "read_timeout" per config_kwargs, the S3FileSystem can not be created. This is unexpected behaviour in so far as the the config_kwargs parameter suggests that every field of the session config can be configured.
The reason for this is that these two values are hardwired into the boto config object:
```
conf = Config(connect_timeout=self.connect_timeout,
read_timeout=self.read_timeout,
**self.config_kwargs)
```
This will lead to the following error, if "connect_timeout" or "read_timeout" are part of the config_kwargs: 
```
TypeError: type object got multiple values for keyword argument …
```
=> Make S3FileSystem read_timeout and connection_timeout configurable

s3fs/core.py, s3fs/tests/test_s3fs.py
This should in principal allow us to do things like
```
dask.dataframe.read_parquet([
's3://bucket/somepath/file_part0001.parquet?versionId=ksfgsdkfkjadsf',
's3://bucket/somepath/file_part0002.parquet?versionId=lijserslifhsdiu',
])
```
This should work for most things that make sense.
Not everything has proper test cases yet.
=> Specify an s3uri as {bucket}/{key}?versionId={versionId}

s3fs/core.py, s3fs/tests/test_s3fs.py
Since 0.4.1 I am unable to provide credentials via the client_kwargs argument.
```
s3 = S3FileSystem(client_kwargs={'aws_access_key_id': 'foo', 'aws_secret_access_key': 'bar'})
>  TypeError: create_client() got multiple values for keyword argument 'aws_access_key_id'
```
This was caused by the following change in s3fs.core (lines 292-293):
```
self.s3 = self.session.create_client('s3', aws_access_key_id=self.key, aws_secret_access_key=self.secret, aws_session_token=self.token, config=conf, use_ssl=ssl,
**self.client_kwargs)
```
My PR would allow the use of either using the arguments (`key`, `secret`, `token`) or the `client_kwargs`.
It would also allow a combination of both. E.g. key + client_kwargs['aws_secret_access_key']
I do allow repeating the same argument in both (e.g. key + …
=> allow credentials in client kwargs

docs/source/index.rst
Documentation for #120 
I was looking for a solution to the very same problem as is described in the issue #120. It seems that:
1) I'm not alone with this usecase.
2) Nobody really likes to write the documentation.
Let's save the future users some time. :slightly_smiling_face:
=> Add Self-hosted S3 section to the docs

s3fs/tests/test_s3fs.py
This adds a test case for issue 303, which was fixed in release 0.4.2 (thanks @martindurant).
I have confirmed it fails on the previous code (without the fix to `info()`)
=> add test for issue 303

s3fs/core.py
Address performance issue discuss in https://github.com/dask/s3fs/issues/320.
Update info() method to use list_objects_v2(maxKey=1) to determine whether a particular path is a directory not.
It will try to avoid calling super.info(), this will result pretty expensive operations.
=> Address info() performance issue

s3fs/core.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it in just 2 cases for now.
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …
=> Fix 2 exception causes in core.py

s3fs/core.py, s3fs/tests/test_s3fs.py
- mkdirs is called by https://github.com/apache/arrow/blob/master/python/pyarrow/filesystem.py#L336
=> Implement fsspec makedirs

s3fs/core.py, s3fs/tests/test_s3fs.py
checksum() fails if the object is created using the multipart upload feature of S3. This is because the resulting ETag is in a slightly different format: _hash_-_num_parts_. This PR addresses the problem by parsing the _hash_ part only and discarding the rest.
=> Fix checksum for multipart uploads

s3fs/core.py
When trying to use an aws profile I ran into problems.
Looking into it the session argument is not used in the initialisation.
Therefore if the argument is provided it should be used
=> Added session handling in S3FileSystem

s3fs/core.py, s3fs/tests/test_s3fs.py
Currently when creating a `S3FileSystem` with `asynchronous=True`, an error is raised as we're trying at access the `.s3` property prior to creating an S3 client:
```python
In [1]: import s3fs
In [2]: s3 = s3fs.S3FileSystem(asynchronous=True)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-59def4c342c4> in <module>
----> 1 s3 = s3fs.S3FileSystem(asynchronous=True)
~/miniforge3/envs/s3fs-dev/lib/python3.8/site-packages/fsspec/spec.py in __call__(cls, *args, **kwargs)
53             return cls._cache[token]
54         else:
---> 55             obj = super().__call__(*args, **kwargs)
56             # Setting _fs_token here causes some static linters to complain.
57 …
```
=> Ensure S3 client exists before creating S3 keyword helper

s3fs/core.py
Counterpart to https://github.com/dask/gcsfs/pull/280
Probably
fixes #359 
fixes #358
=> Do find without recursion

s3fs/core.py
This will enable downstream classes to specify how to sign urls, providing short term URLs for situations where the URL is needed but permissioning needs to be tightly controlled.
Note that currently this adds a boto3 dep, which I'd like to discuss.
xref: https://github.com/intake/filesystem_spec/pull/376
=> add sign to filesystem class

s3fs/core.py
Hello s3fs maintainers! I ran into the same issue raised in #330. It pops up when I try to use `object_version_info` for a prefix with more versions than can fit in a single API response. This change resolves that issue.
Long-time happy user / first-time contributor here... so let me know if you have any questions/comments/etc about the change. Thanks!
=> Add key marker for paginated version info calls

s3fs/core.py, s3fs/tests/test_s3fs.py
Added a test to verify that the find method respects the maxdepth
parameter.  With ``maxdepth=1``, the results of ``find`` should be
the same as those ``ls``, without returning subdirectories.  See also
issue 378.
=> Test for #378 to verify find respects maxdepth.

s3fs/core.py
Some s3 server implementations such as OpenStack Object Storage
("Swift") don't provide the field KeyCount in the response to list_object_v2.
This change handles this gracefully and reverts to checking other keys
("Contents" and "CommonPrefixes").
See https://github.com/dask/s3fs/issues/404 for more details.
=> Handle list_object_v2 calls with missing KeyCount

README.rst
instead of botocore documentation
requirements.txt no longer points to botocore as its core dependency
=> README.rst update to point to aiobotocore documentation i

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Avoid adding parent dir in find

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes #433
I created the test first and verified that it failed without the fix in `_cat_file`.
=> Allow for zero start in _cat_file

.github/workflows/ci.yml, test_requirements.txt
I didn't had chance to debug it fully though moto>2.0 is incompatible with the tests as is (2 version check tests are failing) intake/filesystem_spec/pull/557
=> setup: pin moto to under 2.0

s3fs/core.py, s3fs/tests/test_s3fs.py
=> copy: implement preserve_etag mode

setup.py
=> add passthrough extras for boto3 and awscli

s3fs/core.py, s3fs/errors.py, s3fs/tests/test_s3fs.py
=>  Prevent recursion on error translation 

docs/source/index.rst, s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes #454 
This renames `_connect` to `set_session` and provides an implementation of `_connect` for backward compatibility. The documentation are tests are updated, too.
=> Rename _connect to set_session

docs/source/index.rst
Per the [`boto3` docs](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#environment-variables), the environment variables for credentials need to be uppercase. If I set lowercase env variables on my machine (OSX), I get the a `NoCredentialsError: Unable to locate credentials`.
=> Docs: Change env variables to upper case

requirements.txt, s3fs/core.py
`fsspec.utils.setup_logging` doesn't appear to be used anywhere in s3fs.core (it's redefined almost immediately after the import). 
`fsspec==0.9.0` has the function `fsspec.utils.setup_logging` but earlier versions do not (it was renamed from setup_logger->setup_logging in `0.9.0`). The tests for `main` seem to be passing on `fsspec>=0.9.0` but the install requirements have `fsspec>=0.8.0`. It seems like the options are either bump the fsspec version to 0.9.0 or remove the unused import. 
I'm happy to make any necessary changes.
=> fix import error

s3fs/core.py, s3fs/utils.py
=> spec: implement bucket region caching

s3fs/core.py, s3fs/tests/test_s3fs.py
Now it supports `.find(prefix=None)`
=> cast all non-truthy prefixes to an empty string

requirements.txt, s3fs/core.py, setup.py
Since https://github.com/aio-libs/aiobotocore/releases/tag/1.4.0, `AioSession` no longer exists in the top-level namespace. This PR also:
- pins the **aiobotocore** dependency more strictly, since the project demonstrated that it will do backwards-incompatible changes with a minor bump, and
- pins the `extras_require` dependencies; they were previously unpinned.
My local test runs are failing but I _don't_ think its due to this change (they were failing on **main**) so apologies if CI fails.
=> Aio session is no longer top level

s3fs/core.py
Addresses the #issue 194. S3fs propagates IncompleteRead error when the network is flaky. 
This error was previously removed by large:
https://github.com/boto/boto3/commit/d02dc9b57ae28ccb2265dcf1e560afd7dbad8098#diff-6e0c1dbf251dce0fe05f05e3dc7645cdL150
Not sure if it was intentional.
=> Add IncompleteRead to a set of retryable errors

s3fs/core.py
Hej hej!
Currently the expected behavior of `glob("*")` is to throw an exception.
But this behavior currently relies on private implementation details of `fsspec` which are orthogonal to `s3fs`.
This pull request removes this implicit dependency, so that both projects can continue to develop in parallel.
=> made glob raise exception on *

s3fs/core.py
For some use cases, we need to generate a presigned url for uploading files, and for which we need to change the `ClientMethod` to `put_object`.
=> Allow passing client_method to url() and sign()

s3fs/core.py
Downstream users and libraries may need to pass `cache_options` (along with `cache_type`) to the back-end cache when an `S3File` instance is created. This is especially true for the`"parts"` cache (`KnownPartsOfAFile`) and the new `fsspec.parquet.open_parquet_file` optimization that uses it.
=> Pass through cache_options to S3File

.github/workflows/ci.yml, requirements.txt
Motivation of PR here: https://github.com/fsspec/s3fs/pull/554#issue-782315055
This picks up aiobotocore==1.4.2 in the CI: https://github.com/fsspec/s3fs/runs/4240157139?check_suite_focus=true#step:4:527
Currently CI grabs aiobotocore==1.4.1 e.g. https://github.com/fsspec/s3fs/runs/4228322835?check_suite_focus=true#step:4:37 which is from #552
=> simple pin of aiobotocore in requirements.txt and ci.yml

s3fs/core.py
=> Fix #477 -- Don't set IfMatch if ETag is missing

docs/source/index.rst
Some s3-compatible object storage provider require specific
configuration parameters when instantiating `s3fs`.
This commit adds some configuration examples for ovh and scaleway.
closes #566
=> docs: Improves docs for s3-compatible storage

s3fs/core.py, s3fs/tests/test_s3fs.py
```
fs = s3fs.S3FileSystem()
with fs.open("s3://my-bucket/my/file", "w", acl="bucket-owner-full-control") as f:
f.write("test")
```
=> fixes: acl not set for small files

.github/workflows/ci.yml, requirements.txt
aiobotocore is one of the dependencies of s3fs.
I have updated aiobotocore from 2.0.1 to the latest 2.1.0.
[Background]
boto is used by many different libraries, so it is difficult to lock the boto version.
When I use botocore 1.23.0 or later, I face and opened this issue https://github.com/aio-libs/aiobotocore/issues/905
And this issue has been resolved by this PR https://github.com/aio-libs/aiobotocore/pull/909
Updated version was released with aiobotocore 2.1.0 So I want to use this version from s3fs.
I'll show the log after applying my PR.
Before
```
>>> import s3fs
>>> fs = s3fs.S3FileSystem()
>>> fs.ls('hayshogo-s3')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/hayshogo/.local/lib/python3.9/site-packages/fsspec/asyn.py", line 91, in wrapper …
```
=> bump aiobotocore to 2.1.0

s3fs/core.py, s3fs/tests/test_s3fs.py
This PR adds the content type to uploaded objects by populating the "ContentType" kwarg using mimetypes. I'm not sure how to test this and also unsure about if anything extra is needed for multipart, would love clarity on that.
tested with 
```
pytest s3fs/tests/test_s3fs.py -k test_content_type
```
=> Set content type on upload

docs/source/development.rst
I'm would like to add this page as I have to recently (re)think about create a development environment and running tests.
My goal is this would be copy-pastable to help new contributors.
I imagine this could be expanded in the future e.g. https://docs.dask.org/en/stable/develop.html#install
=> add development page to docs

test_requirements.txt
moto recently released version 3, that broke our CI https://github.com/fsspec/filesystem_spec/runs/5139980542?check_suite_focus=true
Looks like moto 3 could be swallowing some headers, so playing it safe with 2.0 for now.
=> tests: limit moto <3

.pre-commit-config.yaml, s3fs/tests/test_s3fs.py
Closes #317
@sweco - the test seems to show that the functionality is working as expected. If in your case, you *also* have an empty key directory placeholder key, then I this it is reasonable that it isn't automatically deleted, and you should need to issue `rm` on the key again (because they key is not contained within the directory).
=> Add recursive rm test

s3fs/core.py
I'd really like to use backoff for this (https://pypi.org/project/backoff/), but for now this seems like a good simple implementation that is compatible with the existing implementation.
I added `FSTimeoutError` to the list of retryable errors as I've seen this also pop up when S3 is under load.
=> Add retries to _cat_file and _get_file. Closes #537

.github/workflows/ci.yml, requirements.txt
=> aiobotocore to 2.3.0

docs/source/index.rst
Without this, the code sample is just hidden
From https://s3fs.readthedocs.io/en/latest/index.html?highlight=minio#s3-compatible-storage
=> Fix syntax error hiding minio code sample

requirements.txt
It is not possible to run `pip install --pre s3fs` right now because the two latest pre-releases of `aiohttp` are broken (v4.0.0a0 and v4.0.0a1).
This PR proposes excluding these two versions from the s3fs requirements.
More details: https://github.com/fsspec/filesystem_spec/pull/1018
=> Fix `pip install --pre s3fs`

s3fs/tests/test_s3fs.py
Recently came across some logging for the moto server in intake-xarray (https://github.com/intake/intake-xarray/blob/master/intake_xarray/tests/test_remote.py#L162) wanted to upstream it here.
=> some moto logging

s3fs/core.py, s3fs/tests/test_s3fs.py
Added a slightly modified version of the find_bucket_key from [awscli](https://github.com/aws/aws-cli/blob/733f856ebdfc59edad6f4b7242b7027eeecec7d0/awscli/customizations/s3/utils.py#L217) ensure that the bucket name and paths are split properly
=> Added a slightly changed version from the awscli find bucket function

s3fs/core.py
Fixes #651 
@Eugeny, can you please test? You seemed to be hitting a corner case where list-from-cache returned None a moment after just having checked that the value was not in fact None. Now we only call once.
=> If listing expires between checking it, and using it

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes https://github.com/fsspec/s3fs/issues/653
- Version aware filesystems use `list_object_versions` instead of `list_objects_v2` for listing directories
- `fs.dircache` will only cache entries for the latest file versions (file versions with `IsLatest == True`)
- Individual file lookups (via `_info`) will return the cached version when the requested version is latest (when requested `version_id is None`)
- When `_info` is doing a lookup for a specific (non-`None`) version_id, it will check if the cached version matches and then make the required `HeadObject` call if needed.
=> find/ls: use list_object_versions instead of list_objects_v2 for version aware filesystems

s3fs/core.py
Hi all, greetings from Polars... 
We had an issue (https://github.com/pola-rs/polars/issues/5451) raised just now, relating to #662 here. I've started debugging this on our side; we make use of `importlib`'s [LazyLoader](https://docs.python.org/3/library/importlib.html#importlib.util.LazyLoader) class to defer loading several modules, with `fsspec` being amongst them.
I've spotted a one-liner you can add which fixes the issue at (apparently) no cost, and it will guard against similar gremlins if anyone else lazy-loads `fsspec` - just to be clear, I will keep looking for a lower-level solution on our side, as it shouldn't really be on you to handle somebody else lazy-loading  ;)
As you can tell from the simplicity of the patch, the jump straight to submodule imports appears to bypass the …
=> Allow use of `s3fs` when `fsspec` is mediated by a `LazyLoader`

docs/source/index.rst
Two external links are not rendering properly due to a simple rst typo.
=> Fix link syntax

s3fs/core.py
When dealing with large directories, using `_ls()`/`_lsdir()` forces us to wait until all the contents of the directory have been received, which can take a significant amount of time. This PR creates an `_iterdir()` async iterator which allows the results to be handled as soon as they're received from the network.
=> Create async iterator version of _lsdir()

s3fs/utils.py
For freshly created S3 buckets, boto `head_bucket` will fail with `ERR An error occurred (403) when calling the HeadBucket operation: Forbidden` even though ResponseMetadata will contain the correct region header - for up to an hour in my experience.
This PR adds handling for this and continues if the region header is present despite HeadBucket failing.
=> Handle temporary errors in HeadBucket

docs/source/index.rst
This PR simply updates the documentation to add Storj DCS (https://github.com/storj/storj) as an explicit S3-compatible (supported) method for S3Fs.
Storj DCS is a distributed and open-source cloud storage network that is becoming popular for Hugging Face developers for Datasets – due to it's global availability coupled with an empirically better security and economic model.  
Thanks – and also excited to add S3Fs as a reference within the Storj docs as a "how-to" after merge, as reciprocity!
=> Add Storj DCS as an explicit endpoint for S3-compatible storage

setup.py
Change minimum python version from 3.7 to 3.8, in line with fsspec/filesystem_spec#1184 and  fsspec/filesystem_spec#1185. It was already correct in the classifiers.
=> Set minimum python to 3.8

docs/source/index.rst, s3fs/core.py
Currently, if you're using non-AWS S3 endpoint you're stuck with less ergonomic syntax, see https://github.com/fsspec/s3fs/issues/120#issuecomment-647117380 for example.
Sometimes it's feasible, but sometimes it breaks flexibility that `fsspec` provides.
This simple PR makes `endpoint_url` a first-class configuration option, alongside with `key` and `secret`, which are already supported exactly in the same way.
=> Enable providing `endpoint_url` through environment variables

requirements.txt
Bumps aiobotocore to 2.5.0 to resolve a dependency conflict I'm seeing with a package that depends on the latest boto3.
=> bump aiobotocore to 2.5.0

s3fs/core.py
S3AsyncStreamedFile seems to be defined twice in line s3fs/core.py#2292-2320
This PR removes the second definition.
=> Remove duplicate class S3AsyncStreamedFile

docs/source/index.rst
Aligns with the other examples on the page. `s3fs.S3FileSystem` object is assigned the name `s3` for all other examples
=> Conform variable name in example 

s3fs/core.py
When doing _put_file with small files, a retryable error like `SlowDown` could ultimately result in `BadDigest` failures.
The `botocore` code would read the entire file passed into `put_object`. The `error_wrapper` would then retry with the same file object but nothing would seek back to the start again.
This is now fixed by not using a file object but, similar to the multi-part upload, read the content into bytes first. These bytes can be retried without seeking. This resolves the problem.
=> Fix bug were SlowDown retries could result in BadDigest failures for small files

.github/workflows/ci.yml, s3fs/tests/derived/s3fs_fixtures.py, s3fs/tests/derived/s3fs_test.py
This adds testing using the abstract test harness introduced into `fsspec` in fsspec/filesystem_spec#1216. It is not intended to be merged yet, my intention is to leave it as an open PR that I can keep pushing to and rerun the CI as I add more tests to `fsspec` that will be picked up here.
It demonstrates what is required for a class derived from `fsspec.AbstractFileSystem` to inherit and run the new test suite. The `s3fs_test.py` file will run all tests from the `fsspec.Abstract<whatever>Tests` by inheriting from them. If a test is not appropriate for this `fsspec` implementation then it would be `pytest.skipped` in this file. Most of the new code is setting up a filesystem in a repeatable way for the tests, and most of this is copy-and-pasted (with minor modifications) from the …
=> Test using new abstract test harness

s3fs/tests/derived/s3fs_fixtures.py
I accidentally left a `print` statement in PR https://github.com/fsspec/s3fs/pull/713, this removes it. It wouldn't have done any harm as it is only in the test code, but I should certainly have checked more carefully.
=> Remove unwanted print statement

test_requirements.txt
When installing `requirements.txt` and `test_requirements.txt`, `moto_server` cannot start as it is missing the `flask_cors` dependency:
```
(env) hemker@machine:~/dev/s3fs [main]$ moto_server s3 -p 5555
/home/hemker/dev/s3fs/env/lib/python3.10/site-packages/moto/moto_server/werkzeug_app.py:13: UserWarning: When using MotoServer, ensure that you install moto[server] to have all dependencies!
warnings.warn(
Traceback (most recent call last):
File "/home/hemker/dev/s3fs/env/bin/moto_server", line 5, in <module>
from moto.server import main
File "/home/hemker/dev/s3fs/env/lib/python3.10/site-packages/moto/server.py", line 10, in <module>
from moto.moto_server.werkzeug_app import (
File "/home/hemker/dev/s3fs/env/lib/python3.10/site-packages/moto/moto_server/werkzeug_app.py", line 9, in …
```
=> Add flask_cors as explicit test dependency

docs/source/index.rst
The classes are now active links to the API
=> add rst links to API

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes #761.
`_rm()` invalidates the cache whereas `_rm_file()` did not but now does.
=> Invalidate cache in rm_file

s3fs/core.py
=> fix: set default acl to private for r2 compatibility

s3fs/core.py, s3fs/tests/derived/s3fs_fixtures.py, s3fs/tests/test_s3fs.py
This PR updates the `s3fs` implementation to support updates made in the [Better double asterisks ** support](https://github.com/fsspec/filesystem_spec/pull/1329) pull request in the `filesystem_spec` repo.
Successful run: https://github.com/fsspec/filesystem_spec/actions/runs/5847462518/job/15915309957
=> Better double asterisk support

s3fs/core.py
Closes https://github.com/fsspec/s3fs/issues/786
The `_call_and_read` pattern was already implemented for `_cat_file` in https://github.com/fsspec/s3fs/pull/601 so I'm just applying this pattern again. I don't know the library well enough to judge if this can be refactored somehow else but I would prefer to separate fix from the refactor
=> Fix `ClientPayloadError` while reading

s3fs/core.py, s3fs/tests/test_s3fs.py
This is a fix for #672
Creates a local `part_header` dictionary, then checks if the `ChecksumSHA256` should be added. 
While this fixes my specific issue, there are probably other headers that should be checked for and added if they exist.
=> Fix for issue #672

.github/workflows/ci.yml
Remove warnings in CI:
- Replace deprecated `mamba-org/provision-with-micromamba` with `mamba-org/setup-micromamba`.
- Specify `python-version` in `lint` action.
- Update versions of actions that are using deprecated `node12`.
=> Remove CI warnings

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes #773.
The `dircache` was inconsistent when calling `find` with different `maxdepth` values. The fix is to ensure that `_find(maxdepth=None)` explicitly adds entries for each found directory under its parent directory key to make it consistent with `_find` that uses integer `maxdepth` and has a different code path.
I think this is another consequence of `s3fs` directories not really existing so they need special handling.
=> Ensure dircache directories contain their subdirectories

s3fs/tests/test_s3fs.py
Hi there! Moto maintainer here. I had a look at the tests for `s3fs`, and realized that there is a cleaner way to use the Moto library for your usecase.
The ThreadedMotoServer starts an instance of MotoServer in the background, achieving the same result as calling `moto_server s3` in a subprocess. So the behaviour is the same, it just hides the nasty details like calling `subprocess.Popen`, and having to manually call `requests.get` to verify whether the server is ready.
The second change is to turn the `s3_base` fixture into a module-scoped fixture. The ThreadedMotoServer will now only be created once per module (file), meaning that the tests are executed much faster (~3mins vs ~5 mins).
Because we do expect a clean slate in between tests, I added `reset_s3_fixture` - calling the …
=> Admin: Improve moto usage, simplifying and speeding up tests

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes #689.
This implements the fix proposed in #689 which looks good to me.
=> Correct rmdir when not just a bucket

requirements.txt
2.7 contains [up to date botocore](https://github.com/aio-libs/aiobotocore/pull/1037) dependencies and support for urllib3 2.0. Increasing the version here should save some dependency headaches (I know it will for me!).
=> Update requirements.txt For aiobotocore 2.7

s3fs/core.py
Hello,
this PR makes `S3FileSystem` more spec compliant by changing the protocol type from `list[str]` to `tuple[str, ...]` as required by fsspec: 
https://github.com/fsspec/filesystem_spec/blob/6aa8a9a888f8d7ce2c721f6896f1ffabde84ef05/fsspec/spec.py#L107
This caused an issue when I was using s3fs together with ReferenceFileSystem. See fsspec/filesystem_spec#1395
Let me know if I should also add some sort of test to ensure the protocol type.
Cheers,
Andreas
=> Make S3FileSystem.protocol type tuple[str, ...]

s3fs/tests/test_s3fs.py
Closes #450.
The problem resported in the issue has already been solved, this PR adds an explicit test for it.
=> Add test for du of non-existent directory

s3fs/core.py
This PR addresses the issue where a KeyError is raised because the `LastModified` attribute is not on a retrieved object
=> Use .get for LastModified to mitigate KeyError

s3fs/core.py, s3fs/tests/test_s3fs.py
=> return offset-aware modification time

s3fs/core.py, s3fs/tests/test_mapping.py, s3fs/tests/test_s3fs.py, s3fs/utils.py
This PR tries to use anon=True if no credentials are supplied or found in config files
The print statement should probably be changed to a warning also help with the tests would be appreciated.
=> Try anon=True if no credentials are supplied or found

s3fs/core.py
cc https://github.com/fsspec/s3fs/issues/831
@kwohlfahrt , can you try with this, please?
=> Don't assume attributes after connect

s3fs/core.py, s3fs/tests/test_s3fs.py
The info function retrieved the `fullpath` from the cache in its initial lookup but used the given `path` (which is a user given variable) on the second instance.
Fixed it to use `fullpath` both times.
You can reproduce the bug with the following code:
```python
fs.isdir("/bucket")
print(fs.dircache._cache)
print(fs.info("/bucket/file"))
```
=> Fix the cache lookup in _info

s3fs/core.py
- Adds `max_concurrency` parameter which can be used to increase the concurrency for multipart uploads during `S3FileSystem._put_file()` (behaves the same as `max_concurrency` for uploads in adlfs)
- `max_concurrency` can be set at the fs instance level or at as a parameter passed to `_put_file()`
- When set, this will stack multiplicatively with `fs.put(batch_size=...)`, so you will end up with a maximum of `max_concurrency * batch_size` parts being transferred at once
- This does not affect downloads/`_get_file()`.
=> put_file: support concurrent multipart uploads with max_concurrency

s3fs/core.py
Fixes #855 - see there for details
=> Feat: retries connection-related ClientError types

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes https://github.com/iterative/dvc-s3/issues/80
It is similar to `gcsfs` and `adlfs`.
On our end it seems `max_concurrency` is passed here https://github.com/iterative/dvc-objects/blob/main/src/dvc_objects/fs/generic.py#L210 and since the new version has this attr we pass it now, which most likely leads to this error.
I'm not sure why `_gef_file` part was not yet implemented. @pmrowla might have a better idea on was it complicated, or less priority. It seems it is the natural next step to do so.
=> fix(core): accept kwargs in get file

s3fs/core.py
Retry the request when we get the error (reduce your request rate).
We have 2000+ tasks, each running in the K8s pod and uploading multiple files to a certain bucket. We get `reduce your request rate` error because s3fs doesn't retry this request
https://stackoverflow.com/questions/46787072/s3-slowdown-please-reduce-your-request-rate-exception
=> fix(s3fs): Consolidate retry logic for rate limits

s3fs/core.py
Fixes https://github.com/fsspec/filesystem_spec/issues/1557
_bulk_delete returned None (no return) when pathlist is empty which is incompatible with the list returned in normal operation. This causes a bug in fsspec for instance, because a list was expected. This change returns an empty list when pathlist is empty
=> _bulk_delete must always return a list, even when pathlist is empty

s3fs/core.py, s3fs/tests/derived/s3fs_fixtures.py, s3fs/tests/test_s3fs.py
Increases default file block size to 50MB
=> Concurrency in pipe()

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Be sure to invalidate cache for both branched of pipe_file

s3fs/core.py, s3fs/tests/test_s3fs.py
The `_upload_file_part_concurrent` method is used as part of the `put_file` function to upload the file in multiple parts (when the file is larger than a certain limit).
The function basically reads from the original file in chunks (by default 50MB) and then schedules 10 upload calls in one block. It has two different "branches": if there is more than one chunk left, it schedules them in parallel - if not, it just runs it directly. 
This last branch has a bug: it uses a variable `chunk` which is actually defined in another scope (in the for-loop before it). This leads to wrong data on the remote location: if you upload a file which has e.g. between 20 * 50MB and 21 * 50MB size, it will always be truncated to to exactly 20 * 50MB on s3. This bug is fixed in this PR.
=> Fix a bug in the `_upload_file_part_concurrent method`

s3fs/core.py, s3fs/tests/test_s3fs.py
Parsing S3 access point URI, like `s3://arn:aws:s3:us-west-2:1234:accesspoint/abc/123.jpg`, causes problems in `fsspec.utils.infer_storage_options` because the `:accesspoint` was parsed as port number.
This patch removes the need to call `fsspec.utils.infer_storage_options` in s3fs, as discussed in https://github.com/fsspec/filesystem_spec/pull/1743#issuecomment-2460232401
=> Parse the query parameter of url without using infer_storage_options

s3fs/core.py, s3fs/tests/test_s3fs.py
* check if path is a directory only if '(not out and key) and not prefix'
Fixes #911
=> fix a bug in the `_find`

s3fs/core.py
=> Smaller thresholds for copy_managed

.github/workflows/ci.yml, s3fs/core.py
Looks like the defaults were changed in #901 but docstring was missed.
=> Update defaults in docstring

.github/workflows/ci.yml, s3fs/tests/derived/s3fs_test.py, s3fs/tests/test_s3fs.py
Perhaps this is intentional (if so feel free to close this PR) but it looks like only one test is being selected to run with the rest being skipped. Suspect that is not wanted.
=> re-enable all tests in CI

s3fs/utils.py
In some cases `x-amz-bucket-region`. E.g. Yandex S3 returns these headers:
```
'server' = 'nginx'
'date' = 'Sat, 11 Jan 2025 18:24:12 GMT'
'content-type' = 'application/xml'
'connection' = 'keep-alive'
'keep-alive' = 'timeout=60'
'x-amz-request-id' = '427d58f44ef55822'
```
We do have a logic to disable region caching if custom endpoint of region are specified:
```python
for parameters in (config_kwargs, self.kwargs, init_kwargs, client_kwargs):
for option in ("region_name", "endpoint_url"):
if parameters.get(option):
self.cache_regions = False
break
else:
cache_regions = self.cache_regions
```
But it won't work if endpoint is specified via env var, or S3 config file (or some other complicated or even dynamic logic that boto is relying internally?). If someone has an idea how to get an …
=> fix(region cache): x-amz-bucket-region can be missing for s3 compatible

s3fs/core.py, s3fs/tests/derived/s3fs_test.py, s3fs/tests/test_s3fs.py
Prior to this change the exclusive write mode "x" did not behave properly for small files, instead acting the same as "w".
This change solves that by passing the IfNotMatch header to put_object even when writing small files that don't require a multipart upload.
Fixes https://github.com/fsspec/s3fs/issues/973
Tested by running the test script linked in the issue as well as updating the unit tests.
=> core.py: fix exclusive write for small files

s3fs/core.py, s3fs/tests/test_s3fs.py
In #961 @martindurant mentions that it would be nice to handle the case where no key is specified and use `head_bucket` to gather more information about the bucket. (https://github.com/fsspec/s3fs/pull/961#issuecomment-2847836001)
This PR implements that and returns the `VersionId` for the bucket. Is there anything else that would be useful to include in here?
=> If no key get bucket info
