fsspec/s3fs

s3fs/core.py
=> Avoid double-close on __del__

s3fs/core.py, s3fs/tests/test_s3fs.py
Introduced FileNotFoundError with ls on a bucket that cannot be accessed
=> Add several tests

s3fs/core.py, s3fs/tests/test_s3fs.py, s3fs/tests/test_utils.py, s3fs/utils.py
Small convenience methods.
Note: the buffer size is the same as the default block-size (currently 5MB).
=> Add get and put methods, just like in hdfs3

docs/source/api.rst, docs/source/index.rst, s3fs/core.py
=> cleanup docstrings and documentation

docs/source/index.rst
=> WIP: Doc updates

s3fs/core.py, s3fs/tests/test_s3fs.py
Special attention to rerely-used length parameter
=> Readline support with pandas additions from PR #18

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Limit cache

s3fs/core.py, s3fs/mapping.py, s3fs/tests/test_mapping.py, s3fs/tests/test_s3fs.py, s3fs/utils.py
See https://github.com/alimanfoo/zarr/pull/22
=> Ensure s3fs works with byte arrays

s3fs/core.py, s3fs/tests/test_s3fs.py
fixes https://github.com/dask/dask/issues/1292
=> added process ID to connection key

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Add signed URL functionality

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Remove s3:// prefix from S3File.__init__

s3fs/core.py, s3fs/tests/test_s3fs.py
If False (not the default), skipping to later in the file beyond the read-ahead,
will not read to fill the in-between. This is appropriate for reading chunks in
the order they occur in the file, but skipping large chunks, e.g., for specific
columns spread through a parquet file.
=> Add fill_cache option to S3File

docs/source/index.rst, s3fs/core.py
Only read-operations are supported
Ran into this trying to access arXiv data (https://arxiv.org/help/bulk_data_s3) for an example of this in the wild.
=> ENH: add support for requester pays buckets

.travis.yml, docs/source/api.rst, docs/source/index.rst, s3fs/core.py, s3fs/tests/test_s3fs.py, s3fs/utils.py
This is a rough POC for allowing us to set various additional kwargs that get used during writing to s3.
Related to #89
=> Support for kwargs in order to support ServerSideEncryption

s3fs/core.py
If subclassing `S3FileSystem`, `current()` should give you an instance of the subclass.
=> Ensure current() uses subclass

.gitignore, .idea/thriftCompiler.xml, s3fs/core.py
https://stackoverflow.com/questions/46980362/store-dask-dataframe-to-csv-with-bucket-owner-full-control-acl
=> Acl special

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Add tagging capability

.travis.yml, s3fs/core.py, s3fs/tests/test_s3fs.py
These are required if an object exceeds 5GB in size.
=> Add copy_managed to use the managed copy functions in boto3

s3fs/core.py, s3fs/tests/test_s3fs.py, s3fs/utils.py
Fixes #122.
I also slightly changed how slashes are treated in some places, squashing multiple consecutive slashes into one. Not sure if that's the desired behavior, though.
=> Change glob()'s treatment of dot and slash

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Allow pickling of instances that themselves came from pickle

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixing issue https://github.com/dask/s3fs/issues/125
=> apply patterns like glob.glob

s3fs/core.py, s3fs/tests/test_s3fs.py
See #135 for full details of bug and solution.
=> Fix issue #135

s3fs/core.py, s3fs/tests/test_s3fs.py
See: https://github.com/dask/s3fs/issues/142
=> Issue 142 - Allow users to provide a botocore session on creation of S3FileSystem

.travis.yml, s3fs/core.py, test_requirements.txt
1. I didnt see any test for the other retry logic so i assume its ok, LMK if this needs a test and what approach to use to simulate the exception
2. to support both py2 and py3 i had to write it like this (as the comments explain). LMK if you want this only on py3 or its ok.
thanks,
Shmulik
=> fix #149 retry ConnectionError on fetch_range

s3fs/core.py
Ensure that we set the version_id after closing a file.
=> Set version_id on a file after writiting

.travis.yml, s3fs/core.py, test_requirements.txt
As discussed on #156, this natural fix breaks the test `test_s3fs.py::test_dynamic_add_rm`.
=> Initial fix

s3fs/core.py
Add possibility to glob for files with refresh.
=> add refresh parameter to glob

.travis.yml, pytest.ini, test_requirements.txt
via pytest-env to ease testing
=> set necessary env vars in pytest.ini

s3fs/core.py, s3fs/tests/test_s3fs.py
=> readinto when buffer is too small

s3fs/core.py
=> Update docstring to S3FileSystem.connect [skip ci]

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes https://github.com/dask/dask/issues/5134
=> invalidate cache to respect protocol and parent

s3fs/core.py
There are two problems. One is #200 , which I have not decided how to solve yet. However, this should get things working OK for you, @AntonFriberg . Would you mind checking?
Fixes https://github.com/dask/dask/issues/5141
=> listbuckets should return empty when permission denied

.travis.yml, docs/source/index.rst, s3fs/core.py
=> Update doc and add kwargs to walk et al

s3fs/__init__.py
Followup to https://github.com/dask/s3fs/pull/227
=> Clean up __version__

s3fs/core.py
Moto (httppretty) and S3 differ in behavior when the range request is like
`range=10-9`. S3 (correctly) ignores the range field, while moto raises.
With this change, we return an empty bytestring. This actually matches
the previous behavior under moto, since we caught InvalidRange (416)
errors and return `b''`.
Closes https://github.com/dask/s3fs/issues/225
=> Skip negative range requests

docs/source/index.rst, s3fs/core.py
=> More logging, and set with env var

s3fs/core.py
Companion to https://github.com/intake/filesystem_spec/pull/146
=> Reinstate PUT for files less than one blocksize

README.rst, docs/requirements.txt, docs/source/index.rst, s3fs/core.py
This PR contains a few minor documentation updates. Namely:
- Adds `sphinx` and `sphinx-rtd-theme` to the doc `requirements.txt` file
- Several small edits (mostly related to using code syntax) in `index.rst`
=> Miscellaneous doc updates

s3fs/core.py, s3fs/tests/test_s3fs.py
Seems boolean logic was hard when I wrote this.
=> Fix mpu preserving behaviour when not using autocommit

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes https://github.com/dask/s3fs/issues/275
=> Fix missing type in info() for version-aware buckets

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes #287 
@mariusvniekerk , I don't think we can ask moto to test this for us - would you?
=> Multipart copy for big files

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes #285 
@rabernat , would you like to test?
=> Let info use HEAD if listing is not cached

s3fs/core.py
Exposing options from https://github.com/intake/filesystem_spec/pull/243
=> Adapt for dircache

s3fs/core.py, s3fs/tests/test_s3fs.py
- Add `modified` method in conjunction with  https://github.com/intake/filesystem_spec/pull/268
=> [WIP] Add modified & simple test

s3fs/core.py, s3fs/tests/test_s3fs.py, s3fs/tests/test_utils.py, s3fs/utils.py
=> Fix for multipart copy one off error

s3fs/core.py, s3fs/tests/test_mapping.py, s3fs/tests/test_s3fs.py
=> Open via fsspec was trying to recreate existing bucket

s3fs/core.py
Also: pass kwargs to AioSession correctly (get_session doesn't
do this, for some reason)
=> Unwind coroutines if aiobotocore balks

s3fs/tests/test_s3fs.py
=> Remember to close session in async test

s3fs/core.py
When attempting to store an xarray `Dataset` in zarr format into my own
minio object-store I was getting the exception BucketAlreadyOwnedByYou
from botocore even though the `makedirs` called had `exist_ok=True`.
Looking at the s3fs source-code it appears this situation wasn't handled
before, but it is now.
=> handle BucketAlreadyOwnedByYou when storing xarray Dataset

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Maybe sync

s3fs/tests/test_s3fs.py
Fixes https://github.com/dask/s3fs/issues/363
=> Test for exists twice

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Close read

s3fs/core.py, s3fs/tests/test_s3fs.py
A version of the bug shown in https://github.com/pydata/xarray/issues/4478
=> Xarray test via dask threads 

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Fixed cached directory info when versioned

s3fs/core.py, s3fs/tests/test_s3fs.py
Fixes #402 
I did some debugging and managed to resolve the issue. I hope this helps.
Any thoughts?
Thanks
=> Return version_id even if file is empty

s3fs/tests/test_s3fs.py
Add test from the linked issue, which was already fixed in #412
Closes #393
=> Add test against #393

s3fs/core.py
This addresses #421. For data of more than twice the chunk size specified for `_pipe_file` and `_put_file`, a multipart upload will be used. The hard limit of 5 GB is also enforced.
=> PUT S3 objects up to 5 GB

docs/source/index.rst
=> DOC: add section on environment variables

s3fs/core.py
For https://github.com/intake/filesystem_spec/pull/586
=> Align with fsspec

docs/source/changelog.rst, requirements.txt, s3fs/tests/test_s3fs.py
=> Updates for release

s3fs/core.py, s3fs/tests/test_mapping.py
Fixes https://github.com/pangeo-forge/pangeo-forge/issues/113
=> _find should not assume dircache

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Handle parent dirs in find

docs/source/changelog.rst, s3fs/core.py, s3fs/tests/test_s3fs.py
Described in https://github.com/dask/s3fs/issues/470#issuecomment-829097599
=> s3: optimize info/exists calls

s3fs/core.py, s3fs/tests/test_s3fs.py
=> copy: drop requirement on etag

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Don't pollute parent dirs in find()

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Make bucket for put(recursive)

s3fs/core.py, s3fs/tests/test_s3fs.py
=> fix: preserve user supplied session in S3FileSystem constructor

docs/source/changelog.rst
Change the last version from 2121.08.0 to 2021.08.0
=> Fix the version

s3fs/core.py
=> Call get_bucket_location before calling list_objects_v2

.github/workflows/ci.yml, s3fs/core.py, setup.cfg
Attempted fix/debug for CI failures
=> Don't cache metadata

s3fs/core.py
Occasionally `aiohttp.ClientPayloadError` can be thrown when reading a response from S3, specifically:
```
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed
``` 
This isn't caught by `s3fs` even though it's definitely a retryable error - it indicates a transient network issue that caused the client to fail to read the complete response. This PR conditionally adds this to the list of retryable exceptions.
=> Mark ClientPayloadError as a retryable exception

s3fs/core.py, s3fs/tests/test_s3fs.py
Add ContentType in fs.info, can be used with mimetypes package
Fixes #569
=> Add ContentType

s3fs/core.py, s3fs/tests/test_s3fs.py
Closes https://github.com/fsspec/s3fs/issues/580
Welcome to continue the convo here on whether this is a good idea of not. As well as if i'm missing anything.
I'll have to address failing tests: https://github.com/fsspec/s3fs/runs/4843522436?check_suite_focus=true#step:6:467
=> drop dup Key and Size returned in _info

.gitignore, s3fs/core.py, s3fs/tests/test_s3fs.py
=> persist metadata on append

s3fs/core.py, s3fs/tests/test_s3fs.py
Hello everyone,
This PR adds the callback keyword argument for both `_get_file` and `_put_file`.
See issue #589
Cheers,
Andreas 😃
=> support callbacks in _get_file and _put_file

requirements.txt
Rel https://github.com/fsspec/gcsfs/pull/450
=> Change pin of fsspec to 2022.2.0 (no leading zeros)

s3fs/core.py, s3fs/errors.py
This commit also fixes issue #598.
- Fixes #597 
- Fixes #598 
Signed-off-by: mvashishtha <mahesh@ponder.io>
=> FIX-#597: Retry on HTTPClientError and don't get items from None error.response.

docs/source/index.rst
=> Add note about multiprocessing start methods

.github/workflows/ci.yml, requirements.txt
In a attempt to solve https://github.com/fsspec/s3fs/issues/558  I am following suggestion from the aiobotocore contributors to update its version to solve the issue https://github.com/aio-libs/aiobotocore/issues/901#issuecomment-1069891573
=> Bumping version of aiobotocore to 2.2.0

s3fs/core.py
This treats `ResponseParserErrors` as retryable, as well as `ClientErrors` if they contain `SlowDown`in the message. This can mitigate/fix #484, and is a non-mutually-exclusive alternative to #619. Where that PR tries to address rate limiting at the request time, this tries to address it in the responses.
In my testing with the snippet [here](https://github.com/fsspec/s3fs/issues/484#issuecomment-1113732081), this helps a lot, but is not a complete fix, as I still often exhaust the default retries. So I might be in favor of *both* this and #619 (or something similar to it based on `asyn._run_coros_in_chunks`)
=> Retry on rate limiting

setup.cfg
see https://github.com/PyCQA/flake8/issues/1750
=> fix flake8 config for flake8 6.0.0

s3fs/core.py, s3fs/tests/test_s3fs.py
See analysis by @sneha5gsm in https://github.com/fsspec/s3fs/issues/677
=> Set default cache type to "readahead"

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Fix find after find

s3fs/core.py, s3fs/tests/test_s3fs.py
=> Implement tell for async stream reader

requirements.txt
referring https://github.com/fsspec/s3fs/issues/801
=> bump requirements.txt

s3fs/core.py
=> fix bugs in _get_file

s3fs/core.py, s3fs/tests/test_mapping.py, s3fs/tests/test_s3fs.py, s3fs/utils.py
Falling back to anon=True was nice (#823), but caused too many breakages. This is the revert.
=> Revert anon fallback

s3fs/core.py
=> pass through glob kwargs
